export const APP_LOADING = 'APP/APP_LOADING';
export const SET_FLIGHT_DATA = 'APP/SET_FLIGHT_DATA';
export const SET_AIRPORT_DATA = 'APP/SET_AIRPORT_DATA';
export const SET_AVAILABLE_ORGS = 'APP/SET_AVAILABLE_ORGS';
